GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/613b6cd04cf9b5b0e3e74fa8

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{ 
    "name": "Sneppy again",
    "number": "38393-777"
}

###
DELETE http://localhost:3001/api/persons/613cc7dafd20653c30e11e86

###
GET https://nameless-sands-54228.herokuapp.com/api/persons

###
GET https://nameless-sands-54228.herokuapp.com/api/persons/5899

###
POST https://nameless-sands-54228.herokuapp.com/api/persons
Content-Type: application/json 

{ 
    "name": "Sneppy the bagel",
    "number": "38393-777"
}

###
DELETE https://nameless-sands-54228.herokuapp.com/api/persons/1

